[package]
name = "miners"
version = "0.1.0"
authors = ["Jon Ihlas <jon.i@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.23.0"
nalgebra = "0.20.0"
rand = "0.7.3"
noise = "0.6.0"
